### ISSUE TITLE
Crashing N Stuff

### ISSUE THREAD

**Issue by Inrixia** [MissPotato/Gears-Of-The-Arcane#10]
**Reproducible in SSP and/or SMP:**  Both
**Client or Server:** Client, sometimes server
**Crash or other:** Crash/Kick Out
**Steps to Reproduce:** Place MFR cables.
**Pack Version:** 1.2.0.10
**Custom mods:** None
**Log:**  http://pastebin.com/ZNH5QmW7

**Other information:**
Here is the crash I get it while flying around my base on the server...

-Edit: merged over to format.

**Comment by MissPotato** [comment]
Fixed in the new version of MFR, have to wait for BuildCraft to release their update as well. (Tomorrow-ish) Could be just looking similar to the bug that was patched. Could also stem from Cauldron. Guess we'll find out tomorrow.
