### ISSUE TITLE
In the newest FTB version of Gears of the Arcane

### ISSUE THREAD

**Issue by LightningThunda** [MissPotato/Gears-Of-The-Arcane#11]
When using NEI to find the recipe or find what an item is used for by clicking on the item (to find the recipe or clicking 'U' button, minecraft instantly crashes with any crash report. It also don't re-open FTB or leave ANY thing relating to the crash as if it never happened?!

**Comment by MissPotato** [comment]
Please follow the format, it makes my job easier. And also, I can not confirm.
