### ISSUE TITLE
crash occures using the osmotic enchanter

### ISSUE THREAD

**Issue by LightningThunda** [MissPotato/Gears-Of-The-Arcane#13]
Opening it or breaking the block does not crash my client BUT as soon as i clicked the enchant button (choosing the enchants does not crash it) the client and the server crash instantly. when the server restarted i managed to extract the wand and the pickaxe with out any consequences (the pick did not enchant) The crash i assume comes from the actual enchants which on ANY tool crashes the server (however my wand cores, giants pick and sword, sickle and amour work fine enchanted without crashing the server)

**Comment by MissPotato** [comment]
I've asked you a few times to use: https://github.com/MrPotatoGaming/Gears-Of-The-Arcane/issues/4
-I already have the log though, so you can skip that part.

**Comment by MissPotato** [comment]
Will be fixed in a future version of Thaumic Tinkers. Once again, please use the form to provide useful information.
