### ISSUE TITLE
Ichor Tools PermBreaking Stuff

### ISSUE THREAD

**Issue by Inrixia** [MissPotato/Gears-Of-The-Arcane#9]
Reproducible in SSP and/or SMP: Both 
Client or Server: Client (I assume Server aswell)
Crash or other: other 
Steps to Reproduce: Start playing, die or place OC robot, try to mine said Robot or Grave with a Awakened Ichor tool that is a mode other than block, watch as block disappears along with your hopes and dreams.
Pack Version: I assume its like 1.0.3.5 Whichever is the latest
Custom mods: Thaumic Tinkerer, OC, Graves Ect
Log: N/A 

Other information: Please Fix this its annoying had to roll back entire server to get lightnings stuff back

**Comment by MissPotato** [comment]
Nothing I can personally do, aside from tell people "don't break certain blocks with Ichor Tools."
